// Code generated by protoc-gen-go.
// source: account.proto
// DO NOT EDIT!

/*
Package account is a generated protocol buffer package.

It is generated from these files:
	account.proto

It has these top-level messages:
	User
	CreateRequest
	CreateResponse
	ReadRequest
	ReadResponse
	SearchRequest
	SearchResponse
*/
package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id       uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Created  string `protobuf:"bytes,4,opt,name=created" json:"created,omitempty"`
	Updated  string `protobuf:"bytes,5,opt,name=updated" json:"updated,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateRequest struct {
	User     *User  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ReadRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ReadResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SearchRequest struct {
	Query  string   `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	Id     []uint64 `protobuf:"varint,2,rep,packed,name=id" json:"id,omitempty"`
	Limit  uint32   `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset uint32   `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type SearchResponse struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SearchResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Account service

type AccountClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
}

type accountClient struct {
	c           client.Client
	serviceName string
}

func NewAccountClient(serviceName string, c client.Client) AccountClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "account"
	}
	return &accountClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *accountClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Account service

type AccountHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
}

func RegisterAccountHandler(s server.Server, hdlr AccountHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Account{hdlr}, opts...))
}

type Account struct {
	AccountHandler
}

func (h *Account) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.AccountHandler.Create(ctx, in, out)
}

func (h *Account) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.AccountHandler.Read(ctx, in, out)
}

func (h *Account) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.AccountHandler.Search(ctx, in, out)
}

func init() { proto.RegisterFile("account.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x52, 0xdd, 0x4a, 0xc3, 0x30,
	0x14, 0x5e, 0xbb, 0x76, 0x73, 0x67, 0x6b, 0x27, 0x61, 0x48, 0xad, 0x08, 0x25, 0x20, 0x4c, 0xc4,
	0x5c, 0xcc, 0x27, 0x10, 0xc1, 0x07, 0x88, 0xf8, 0x00, 0xb1, 0x3d, 0xc3, 0xc2, 0xb6, 0x76, 0x49,
	0x8a, 0x08, 0x3e, 0x81, 0x4f, 0x2d, 0x49, 0x1a, 0xdd, 0x76, 0xe1, 0xe5, 0x77, 0xbe, 0xc3, 0xf9,
	0x7e, 0x12, 0x48, 0x44, 0x59, 0x36, 0xdd, 0x4e, 0xb3, 0x56, 0x36, 0xba, 0xa1, 0x5f, 0x10, 0xbd,
	0x2a, 0x94, 0x24, 0x85, 0xb0, 0xae, 0xb2, 0xa0, 0x08, 0x96, 0x11, 0x0f, 0xeb, 0x8a, 0xe4, 0x70,
	0xd6, 0x29, 0x94, 0x3b, 0xb1, 0xc5, 0x2c, 0x2c, 0x82, 0xe5, 0x84, 0xff, 0x62, 0xb2, 0x80, 0x18,
	0xb7, 0xa2, 0xde, 0x64, 0x43, 0x4b, 0x38, 0x40, 0x32, 0x18, 0x97, 0x12, 0x85, 0xc6, 0x2a, 0x8b,
	0xec, 0xdc, 0x43, 0xc3, 0x74, 0x6d, 0x65, 0x99, 0xd8, 0x31, 0x3d, 0xa4, 0xcf, 0x90, 0x3c, 0xd9,
	0x25, 0x8e, 0xfb, 0x0e, 0x95, 0x26, 0x97, 0x10, 0x19, 0x19, 0x6b, 0x64, 0xba, 0x8a, 0x99, 0xf1,
	0xc6, 0xed, 0xc8, 0x38, 0x6a, 0x85, 0x52, 0x1f, 0x8d, 0xac, 0xbc, 0x23, 0x8f, 0xe9, 0x39, 0xa4,
	0xfe, 0x8e, 0x6a, 0x9b, 0x9d, 0x42, 0x7a, 0x0d, 0x53, 0x8e, 0xa2, 0xf2, 0x77, 0x4f, 0xe2, 0xd1,
	0x5b, 0x98, 0x39, 0xda, 0xad, 0xff, 0xa3, 0x4b, 0x4b, 0x48, 0x5e, 0x50, 0xc8, 0xf2, 0xdd, 0xdf,
	0x5a, 0x40, 0xbc, 0xef, 0x50, 0x7e, 0xda, 0xe5, 0x09, 0x77, 0xa0, 0x57, 0x08, 0x8b, 0x61, 0x5f,
	0xe0, 0x02, 0xe2, 0x4d, 0xbd, 0xad, 0xb5, 0x2d, 0x29, 0xe1, 0x0e, 0x90, 0x0b, 0x18, 0x35, 0xeb,
	0xb5, 0x42, 0x6d, 0x3b, 0x4a, 0x78, 0x8f, 0xe8, 0x3d, 0xa4, 0x5e, 0xa4, 0x77, 0x74, 0x05, 0xb1,
	0x91, 0x57, 0x59, 0x50, 0x0c, 0xff, 0x2c, 0xb9, 0xd9, 0xea, 0x3b, 0x80, 0xf1, 0xa3, 0x7b, 0x47,
	0x72, 0x07, 0x23, 0x97, 0x9d, 0xa4, 0xec, 0xa8, 0xcc, 0x7c, 0xce, 0x4e, 0x4a, 0x19, 0x90, 0x1b,
	0x88, 0x4c, 0x6e, 0x32, 0x63, 0x07, 0xed, 0xe4, 0x09, 0x3b, 0x2c, 0x83, 0x0e, 0xcc, 0x4d, 0x67,
	0x87, 0xa4, 0xec, 0x28, 0x7c, 0x3e, 0x67, 0xc7, 0x3e, 0xe9, 0xe0, 0x6d, 0x64, 0x7f, 0xd2, 0xc3,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x65, 0xb2, 0x7d, 0x8c, 0x5a, 0x02, 0x00, 0x00,
}
